import streamlit as st
import pandas as pd
import time
st.title("hello streamlit")
st.write("hi mrecw")
st.header("byytexl")
st.subheader("bytexl234")
st.text_input("enter your name")
st.number_input("enter your age")
st.text_area("enter your address")
st.slider("select your age",0,100)
st.checkbox("i agree")
options=st.selectbox("select an opition",["option1","option2","option3","option4"])
st.write("you selcted:",options)
st.radio("select your gender",["male","female","other"])
st.sidebar.title("sidebar")
st.sidebar.write("this is sidebar")
st.sidebar.text_input("enter your email")
st.sidebar.selectbox("select your country",["India","Uk","pakistan","Dubai"])
st.image("https://wallpaperaccess.com/full/1871775.jpg")
st.sidebar.image("https://wallpaperaccess.com/full/1871775.jpg")
st.sidebar.slider("select your age",0,5)
col1,col2=st.columns(2)
with col1:
    st.write("Column1")
    col1.text_input("enter your name in column1")
with col2:    
    st.write("Column2")
    col2.text_input("enter your name in column2")
st.text_input("enter your name",type="password")
st.number_input("enter your age",min_value=0, max_value=120,step=2)
st.button("submit")
st.write("[google]","(https://www.google.com)")
st.time_input("select a date")
st.color_picker("pick a color")
st.file_uploader("upload a file")
progress_bar=st.progress(50)
st.header("progrss bar")
st.write("progress completed")
st.balloons()
st.snow()
st.subheader("Spinner")
with st.spinner("waiting.."):
    time.sleep(5)
    st.write("proces completed")
df=pd.read_csv("test.csv")
st.dataframe(df.head())
